[package]
name = "os"
version = "0.1.0"
authors = ["Chris"]

[lib]
crate-type = ["staticlib"]

[dependencies]
flagset = "0.3.0"
volatile = "0.2.6"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
spin = "0.5.2"
bit_field = "0.10.0"
multiboot2 = "0.8.1"
linked_list_allocator = "0.6.4"